In [4]:
import pandas as pd

students = pd.read_csv("data/raw/students.csv")
sessions = pd.read_csv("data/raw/sessions.csv")
quizzes = pd.read_csv("data/raw/quizzes.csv")
completions = pd.read_csv("data/raw/completions.csv")

print(students.shape, sessions.shape, quizzes.shape, completions.shape)

(1500, 4) (20847, 4) (10590, 6) (1500, 6)

In [6]:
students.head()

  student_id enrollment_date   course_id  age
0     S00001      2026-02-17  COURSE_101   29
1     S00002      2026-03-15  COURSE_101   27
2     S00003      2026-02-05  COURSE_101   34
3     S00004      2026-04-18  COURSE_101   24
4     S00005      2026-01-24  COURSE_101   34

In [5]:
sessions.head()

  student_id session_date  module_accessed  session_duration_min
0     S00001   2026-02-19                1                    48
1     S00001   2026-02-21                2                    34
2     S00001   2026-02-24                3                    67
3     S00001   2026-02-25                3                    42
4     S00001   2026-02-26                3                    25

In [7]:
quizzes.head()

   quiz_id student_id  module_number  score  attempts   quiz_date
0  Q000001     S00001              1     69         1  2026-02-19
1  Q000002     S00001              2     69         2  2026-02-21
2  Q000003     S00001              3     71         2  2026-02-24
3  Q000004     S00001              4     68         1  2026-02-27
4  Q000005     S00001              5     61         1  2026-03-02

In [8]:
completions.head()

,student_id,total_modules,modules_completed,completed,last_session_date,dropout_type
0,S00001,10,10,1,2026-03-13,completer
1,S00002,10,2,0,2026-03-18,explicit_dropout
2,S00003,10,5,0,2026-03-23,silent_dropout
3,S00004,10,3,0,2026-05-18,silent_dropout
4,S00005,10,10,1,2026-02-16,completer

In [9]:
completions["completed"].value_counts(normalize=True)

completed
1    0.543333
0    0.456667
Name: proportion, dtype: float64